### ISSUE TITLE
Error while installing a new app after updating dependencies

### ISSUE THREAD

**Issue by ShlomoRuckban** [orel-asper/rn-server-logger#1]
My app does not seem to run when i import the serverLogger from rn-server-logger.

the error i get: 
invariant violation: `new nativeeventemitter()` requires a non-null argument.

**Comment by orel-asper** [comment]
It seems that the issue you are facing is related to the native event emitter in React Native, which requires a non-null argument. The error message suggests that the argument passed to new NativeEventEmitter() is null, causing the invariant violation.

Based on the information you provided, it appears that the issue might be related to a recent update of the react-native-shake library. One possible solution is to use version 5.1.1 of the library without a caret (^) in the dependency.

To fix the issue, you can try the following steps:

Remove the current version of react-native-shake from your project:

npm uninstall react-native-shake

Install version 5.1.1 of react-native-shake without a caret (^) in the dependency:

npm install react-native-shake@5.1.1 --save

Rebuild your project and try importing the serverLogger again.
If this does not solve the problem, you may need to investigate further to determine the root cause of the issue. You can try debugging your code or seeking help from the rn-server-logger or react-native-shake communities for additional support.

**Comment by ShlomoRuckban** [comment]
Hey, 
thanks for the quick response.

your solution works for me.

thanks a lot ^^
